### ISSUE TITLE
Graph bug

### ISSUE THREAD

**Issue by kleem** [nitaku/TEA#2]
An exception is raised when trying to create an entity node as the first node, i.e. if a new directive is created and there isn't any span marked in the text yet.

**Comment by nitaku** [comment]
Wrong comment in commit. Reopening.

**Comment by fabiovalse** [comment]
I debugged the code and the first time you insert a directive without any span you get _TypeError: Cannot read property 'i' of undefined(…)_. The problem is that when the _Document_ model performs the "set graph", _GraphView_ that is listening __does not intercept__ the _change:graph_ event.

**Comment by fabiovalse** [comment]
I debugged the code and the first time you insert a directive without any span you get _TypeError: Cannot read property 'i' of undefined(…)_. Precisely, the error is raised inside the _render_ method of _GraphView_ in the section marked with the comment _###create the position contraints###_.

The problem is line 105:
`n2 = _.find graph.nodes, (n) -> n.longest_dist is depth+1`

The first time depth is zero, so there's no node within _graph.nodes_ having _longest_dist_ equal to 1. The three nodes, _content_, _about_resource_ and _resource_, have respectively zero, two and three as _longest_dist_.

The error is raised at line 108:
`right: n2.i,`
n2 is undefined so _"TypeError: Cannot read property 'i' of undefined(…)"_.

**Comment by fabiovalse** [comment]
I don't know exactly what parameter _i_ means but changing the line 108 with:
`right: if n2? then n2.i else 0,`
fix the problem. Tell me if it is correct so that I'll commit it.
